INSERT INTO record_class (record_type, record_class, vat) 
               VALUES ('Expense', '333 Purchases and inventory changes', 24),
                    ('Expense', '334 External services', 24),
                    ('Expense', '335 Salaries and fees', 0),
                    ('Expense', '336 Pension and personal expenses', 0),
                    ('Expense', '337 Depreciation', 0),
                    ('Expense', '341 Representation expenses', 0),
                    ('Expense', '343 Rents', 24),
                    ('Expense', '344 Travelling expenses', 24),
                    ('Expense', '344 Vehicle expenses', 24),
                    ('Expense', '344 Meeting and negotiation expenses', 24),
                    ('Expense', '344 Other deductible expenses', 24),
                    ('Expense', '346 Interest expenses', 0),
                    ('Expense', '349 Other financial costs', 0),
                    ('Expense', '353 Increases in bookings', 0),
                    ('Expense', '354 Non-accounting deductible expenses', 0),
                    ('Expense', '365 Immediate taxes', 0),
                    ('Expense', '366 Fines and other penalties', 0),
                    ('Expense', '367 Other non-deductible expenses', 0),
                    ('Income', '300 Sales - Finland 24%', 24),
                    ('Income', '300 Sales - Finland 14%', 14),
                    ('Income', '300 Sales - Finland 10%', 10),
                    ('Income', '300 Sales - Finland 0%', 0),
                    ('Income', '300 Sales - EU 0%', 0),
                    ('Income', '300 Sales - Other countries', 0),
                    ('Income', '300 Sales - Reverse tax', 0),
                    ('Income', '301 Other income', 0),
                    ('Income', '312 Reduction of reserves', 0),
                    ('Income', '313 Private use of the car', 0),
                    ('Income', '314 Private use of goods', 0),
                    ('Income', '315 Other private use', 0),
                    ('Income', '317 Tax-free income in the income statement', 0),
                    ('Income', '318 Grants and subsidies received', 0),
                    ('Income', '319 Dividends received', 0),
                    ('Income', '320 Taxable portion of dividends', 0),
                    ('Income', '323 interest income and other financial income', 0),
                    ('Income', '324 Other taxable income', 0)